from eu4.eu4lib import AdditiveModifier, ConstantModifier, MultiplicativeModifier, \
    AdditiveModifierWithPercentageSign

all_modifiers = [
    AdditiveModifier('num_accepted_cultures', ['max promoted cultures']),
    MultiplicativeModifier('adm_tech_cost_modifier', ['adm tech cost']),
    MultiplicativeModifier('advisor_cost', ['advisor cost']),
    AdditiveModifier('advisor_pool', ['possible advisors', 'advisor pool']),
    MultiplicativeModifier('ae_impact', ['aggressive expansion impact', 'ae impact']),
    AdditiveModifier('army_tradition', ['army tradition', 'yearly army tradition']),
    MultiplicativeModifier('army_tradition_decay', ['army tradition decay']),
    MultiplicativeModifier('artillery_cost', ['art cost', 'artillery cost']),
    MultiplicativeModifier('artillery_power', ['art power', 'artillery combat ability', 'artillery power']),
    MultiplicativeModifier('blockade_efficiency', ['blockade efficiency']),
    MultiplicativeModifier('build_cost', ['construction cost']),
    MultiplicativeModifier('development_cost', ['development cost']),
    MultiplicativeModifier('cavalry_cost', ['cavalry cost', 'cav cost']),
    MultiplicativeModifier('cavalry_power', ['cav power', 'cavalry combat ability', 'cavalry power']),
    AdditiveModifier('colonists', ['colonists']),
    MultiplicativeModifier('colonist_placement_chance', ['settler chance', 'colonist chance']),
    MultiplicativeModifier('core_creation', ['core-creation cost', 'core creation cost']),
    MultiplicativeModifier('culture_conversion_cost', ['culture conversion cost']),
    MultiplicativeModifier('defensiveness', ['fort defense']),
    MultiplicativeModifier('dip_tech_cost_modifier', ['dip tech cost']),
    MultiplicativeModifier('diplomatic_annexation_cost', ['diplomatic annexation cost']),
    AdditiveModifier('diplomatic_reputation', ['diplomatic reputation']),
    AdditiveModifier('diplomatic_upkeep', ['diplomatic relations', 'diplomatic upkeep']),
    AdditiveModifier('diplomats', ['diplomats']),
    MultiplicativeModifier('discipline', ['discipline']),
    MultiplicativeModifier('embargo_efficiency', ['embargo efficiency']),
    MultiplicativeModifier('enemy_core_creation', ['hostile core-creation cost on us', 'enemy core creation']),
    MultiplicativeModifier('envoy_travel_time', ['envoy travel time']),
    MultiplicativeModifier('fabricate_claims_cost', ['cost to fabricate claims']),
    AdditiveModifier('free_leader_pool', ['leader(s) without upkeep', 'free leader pool']),
    MultiplicativeModifier('galley_cost', ['galley cost']),
    MultiplicativeModifier('galley_power', ['galley combat ability', 'galley power']),
    AdditiveModifier('global_colonial_growth', ['global settler increase']),
    MultiplicativeModifier('global_foreign_trade_power', ['trade power abroad', 'foreign trade power']),
    MultiplicativeModifier('global_garrison_growth', ['national garrison growth', 'global garrison growth']),
    MultiplicativeModifier('global_heretic_missionary_strength', ['missionary strength vs heretics', 'global heretic missionary strength']),
    MultiplicativeModifier('global_manpower_modifier', ['national manpower modifier', 'global manpower modifier']),
    MultiplicativeModifier('global_missionary_strength', ['missionary strength', 'global missionary strength']),
    MultiplicativeModifier('global_own_trade_power', ['domestic trade power']),
    MultiplicativeModifier('global_prov_trade_power_modifier', ['provincial trade power modifier', 'global prov trade power modifier']),
    MultiplicativeModifier('global_regiment_cost', ['regiment cost']),
    MultiplicativeModifier('global_regiment_recruit_speed', ['recruitment time', 'global regiment recruit speed']),
    AdditiveModifier('global_unrest', ['national unrest', 'global unrest']),
    MultiplicativeModifier('global_ship_cost', ['ship cost']),
    MultiplicativeModifier('global_ship_recruit_speed', ['shipbuilding time', 'global ship recruit speed']),
    MultiplicativeModifier('global_ship_repair', ['global ship repair']),
    MultiplicativeModifier('global_spy_defence', ['foreign spy detection']),
    MultiplicativeModifier('global_tariffs', ['global tariffs']),
    MultiplicativeModifier('global_tax_modifier', ['national tax modifier', 'global tax modifier']),
    MultiplicativeModifier('global_trade_goods_size_modifier', ['goods produced modifier']),
    MultiplicativeModifier('global_trade_power', ['global trade power']),
    MultiplicativeModifier('great_project_upgrade_cost', ['great project upgrade cost']),
    MultiplicativeModifier('heavy_ship_cost', ['heavy ship cost']),
    MultiplicativeModifier('heavy_ship_power', ['heavy ship combat ability', 'heavy ship power']),
    MultiplicativeModifier('heir_chance', ['chance of new heir', 'heir chance']),
    AdditiveModifier('hostile_attrition', ['attrition for enemies', 'hostile attrition']),
    MultiplicativeModifier('idea_cost', ['idea cost']),
    MultiplicativeModifier('imperial_authority', ['imperial authority growth modifier']),
    AdditiveModifier('imperial_authority_value', ['imperial authority modifier']),
    MultiplicativeModifier('improve_relation_modifier', ['improve relations', 'improve relation modifier']),
    MultiplicativeModifier('infantry_cost', ['inf cost', 'infantry cost']),
    MultiplicativeModifier('infantry_power', ['inf power', 'infantry combat ability', 'infantry power']),
    AdditiveModifier('inflation_reduction', ['inflation reduction']),
    AdditiveModifier('interest', ['interest per annum', 'interest']),
    MultiplicativeModifier('justify_trade_conflict_cost', ['cost to justify trade conflict', 'justify trade conflict cost']),
    MultiplicativeModifier('land_attrition', ['land attrition']),
    MultiplicativeModifier('land_forcelimit_modifier', ['land force limit modifier', 'land forcelimit modifier']),
    MultiplicativeModifier('land_maintenance_modifier', ['land maintenance modifier']),
    MultiplicativeModifier('land_morale', ['morale of armies', 'land morale']),
    AdditiveModifier('leader_land_fire', ['land leader fire']),
    AdditiveModifier('leader_land_manuever', ['land leader maneuver']),
    AdditiveModifier('leader_land_shock', ['land leader shock']),
    AdditiveModifier('leader_naval_fire', ['naval leader fire']),
    AdditiveModifier('leader_naval_manuever', ['naval leader maneuver']),
    AdditiveModifier('leader_naval_shock', ['naval leader shock']),
    AdditiveModifier('leader_siege', ['leader siege']),
    AdditiveModifier('legitimacy', ['legitimacy', 'yearly legitimacy']),
    MultiplicativeModifier('light_ship_cost', ['light ship cost']),
    MultiplicativeModifier('light_ship_power', ['light ship combat ability', 'light ship power']),
    MultiplicativeModifier('manpower_recovery_speed', ['manpower recovery speed']),
    ConstantModifier('may_explore', ['may explore']),
    ConstantModifier('may_perform_slave_raid', ['may raid coasts']),
    MultiplicativeModifier('merc_maintenance_modifier', ['mercenary maintenance', 'merc maintenance modifier']),
    MultiplicativeModifier('mercenary_cost', ['mercenary cost']),
    MultiplicativeModifier('caravan_power', ['caravan power']),
    AdditiveModifier('merchants', ['merchants']),
    MultiplicativeModifier('mil_tech_cost_modifier', ['mil tech cost']),
    AdditiveModifier('missionaries', ['missionaries']),
    AdditiveModifier('monthly_fervor_increase', ['monthly fervor', 'monthly fervor increase']),
    MultiplicativeModifier('naval_attrition', ['naval attrition']),
    MultiplicativeModifier('naval_forcelimit_modifier', ['naval force limit modifier', 'naval forcelimit modifier']),
    MultiplicativeModifier('monthly_gold_inflation_modifier', ['monthly gold inflation modifier']),
    MultiplicativeModifier('naval_maintenance_modifier', ['naval maintenance modifier']),
    MultiplicativeModifier('naval_morale', ['morale of navies', 'naval morale']),
    AdditiveModifier('navy_tradition', ['navy tradition', 'yearly navy tradition']),
    MultiplicativeModifier('navy_tradition_decay', ['navy tradition decay']),
    ConstantModifier('no_religion_penalty', ['no religion penalty']),
    AdditiveModifier('papal_influence', ['papal influence']),
    MultiplicativeModifier('mercenary_manpower', ['mercenary manpower']),
    AdditiveModifier('prestige', ['prestige']),
    MultiplicativeModifier('prestige_decay', ['prestige decay']),
    MultiplicativeModifier('prestige_from_land', ['prestige from land']),
    MultiplicativeModifier('privateer_efficiency', ['privateer efficiency']),
    MultiplicativeModifier('production_efficiency', ['production efficiency']),
    MultiplicativeModifier('range', ['colonial range']),
    MultiplicativeModifier('rebel_support_efficiency', ['rebel support efficiency']),
    MultiplicativeModifier('recover_army_morale_speed', ['land morale recovery', 'recover army morale speed']),
    MultiplicativeModifier('recover_navy_morale_speed', ['naval morale recovery', 'recover navy morale speed']),
    MultiplicativeModifier('native_assimilation', ['native assimilation']),
    MultiplicativeModifier('native_uprising_chance', ['native uprising chance']),
    MultiplicativeModifier('reinforce_speed', ['reinforce speed']),
    MultiplicativeModifier('religious_unity', ['religious unity']),
    AdditiveModifier('republican_tradition', ['republican tradition', 'yearly republican tradition']),
    MultiplicativeModifier('ship_durability', ['ship durability']),
    MultiplicativeModifier('siege_ability', ['siege ability']),
    MultiplicativeModifier('spy_offence', ['spy network construction']),
    MultiplicativeModifier('stability_cost_modifier', ['stability cost modifier']),
    MultiplicativeModifier('technology_cost', ['technology cost']),
    AdditiveModifier('tolerance_heathen', ['tolerance of heathens', 'tolerance heathen']),
    AdditiveModifier('tolerance_heretic', ['tolerance of heretics', 'tolerance heretic']),
    AdditiveModifier('tolerance_own', ['tolerance of the true faith', 'tolerance own']),
    MultiplicativeModifier('trade_efficiency', ['trade efficiency']),
    MultiplicativeModifier('trade_range_modifier', ['trade range']),
    MultiplicativeModifier('trade_steering', ['trade steering']),
    MultiplicativeModifier('unjustified_demands', ['unjustified demands']),
    MultiplicativeModifier('vassal_forcelimit_bonus', ['vassal force limit contribution', 'vassal forcelimit bonus']),
    MultiplicativeModifier('vassal_income', ['income from vassals', 'vassal income']),
    AdditiveModifier('war_exhaustion', ['monthly war exhaustion', 'war exhaustion decrease']),
    MultiplicativeModifier('war_exhaustion_cost', ['war exhaustion cost']),
    AdditiveModifier('years_of_nationalism', ['years of separatism']),
    AdditiveModifier('global_autonomy', ['autonomy', 'national autonomy']),
    MultiplicativeModifier('province_warscore_cost', ['province warscore cost', 'province war score cost']),
    AdditiveModifier('devotion', ['devotion', 'yearly devotion']),
    MultiplicativeModifier('church_power_modifier', ['church power', 'church power modifier']),
    MultiplicativeModifier('garrison_size', ['garrison size']),
    MultiplicativeModifier('fort_maintenance_modifier', ['fort maintenance', 'fort maintenance modifier']),
    MultiplicativeModifier('loot_amount', ['looting speed']),
    AdditiveModifier('horde_unity', ['horde unity', 'yearly horde unity']),
    MultiplicativeModifier('global_sailors_modifier', ['national sailors modifier']),
    MultiplicativeModifier('sailors_recovery_speed', ['sailor recovery speed']),
    MultiplicativeModifier('state_maintenance_modifier', ['state maintenance']),
    MultiplicativeModifier('reduced_liberty_desire', ['liberty desire in subjects'], multiply_value_with=-1),
    AdditiveModifier('yearly_corruption', ['corruption']),
    MultiplicativeModifier('global_institution_spread', ['institution spread']),
    MultiplicativeModifier('embracement_cost', ['institution embracement cost']),
    MultiplicativeModifier('movement_speed', ['movement speed']),
    MultiplicativeModifier('shock_damage_received', ['shock damage received']),
    MultiplicativeModifier('army_tradition_from_battle', ['army tradition from battles']),
    MultiplicativeModifier('naval_tradition_from_battle', ['naval tradition from battles']),
    AdditiveModifier('cavalry_fire', ['cavalry fire']),
    MultiplicativeModifier('cavalry_flanking', ['cavalry flanking ability']),
    MultiplicativeModifier('fire_damage', ['land fire damage']),
    MultiplicativeModifier('capture_ship_chance', ['capture ship chance', 'chance to capture enemy ships']),
    MultiplicativeModifier('sunk_ship_morale_hit_recieved', ['morale hit when losing a ship']),
    MultiplicativeModifier('transport_cost', ['transport cost']),
    AdditiveModifier('yearly_harmony', ['harmony increase', 'yearly harmony increase']),
    AdditiveModifier('yearly_absolutism', ['yearly absolutism', 'absolutism']),
    MultiplicativeModifier('cav_to_inf_ratio', ['cavalry to infantry ratio']),
    MultiplicativeModifier('amount_of_banners', ['amount of banners', 'possible manchu banners']),
    MultiplicativeModifier('reinforce_cost_modifier', ['reinforce cost']),
    MultiplicativeModifier('shock_damage', ['shock damage']),
    MultiplicativeModifier('sailor_maintenance_modifer', ['sailor maintenance']),
    MultiplicativeModifier('administrative_efficiency', ['administrative efficiency']),
    MultiplicativeModifier('global_naval_engagement_modifier', ['global naval engagement']),
    MultiplicativeModifier('mercenary_discipline', ['mercenary discipline']),
    MultiplicativeModifier('fire_damage_received', ['fire damage received']),
    AdditiveModifier('monthly_piety', ['monthly piety'], multiply_value_with=100),
    AdditiveModifier('yearly_tribal_allegiance', ['yearly tribal allegiance']),
    MultiplicativeModifier('same_culture_advisor_cost', ['cost of adv wrc']),
    AdditiveModifier('meritocracy', ['meritocracy']),
    MultiplicativeModifier('harsh_treatment_cost', ['harsh treatment cost']),
    MultiplicativeModifier('global_ship_trade_power', ['ship trade power']),
    MultiplicativeModifier('ship_power_propagation', ['ship tradepower propagation']),
    MultiplicativeModifier('build_time', ['construction time']),
    AdditiveModifier('possible_policy', ['possible policies']),
    MultiplicativeModifier('reform_progress_growth', ['reform progress growth']),
    AdditiveModifier('free_adm_policy', ['administrative free policies']),
    AdditiveModifier('free_dip_policy', ['diplomatic free policies']),
    AdditiveModifier('free_mil_policy', ['military free policies']),
    AdditiveModifier('possible_dip_policy', ['diplomatic possible policies']),
    AdditiveModifier('possible_mil_policy', ['military possible policies']),
    MultiplicativeModifier('power_projection_from_insults', ['power projection from insults']),
    MultiplicativeModifier('innovativeness_gain', ['innovativeness gain']),
    MultiplicativeModifier('missionary_maintenance_cost', ['missionary maintenance', 'missionary maintenance cost']),
    MultiplicativeModifier('expel_minorities_cost', ['expel minorities cost']),
    MultiplicativeModifier('naval_tradition_from_trade', ['naval tradition from trade', 'naval tradition from protecting trade']),
    MultiplicativeModifier('admiral_cost', ['admiral cost']),
    MultiplicativeModifier('center_of_trade_upgrade_cost', ['center of trade upgrade cost']),
    MultiplicativeModifier('rival_border_fort_maintenance', ['fort maintenance on border with rival']),
    AdditiveModifier('own_coast_naval_combat_bonus', ['naval combat bonus off owned coast']),
    AdditiveModifier('artillery_fire', ['artillery fire']),
    MultiplicativeModifier('autonomy_change_time', ['autonomy change cooldown']),
    MultiplicativeModifier('backrow_artillery_damage', ['artillery damage from back row']),
    AdditiveModifier('placed_merchant_power', ['merchant trade power']),
    AdditiveModifierWithPercentageSign('liberty_desire', ['liberty desire']),
    MultiplicativeModifier('liberty_desire_from_subject_development', ['liberty desire from subjects development']),
    MultiplicativeModifier('reelection_cost', ['reelection cost']),
    MultiplicativeModifier('female_advisor_chance', ['female advisor chance']),
    AdditiveModifier('siege_blockade_progress', ['blockade impact on siege']),
    AdditiveModifier('imperial_mandate', ['mandate growth modifier']),
    MultiplicativeModifier('nobles_loyalty_modifier', ['nobility loyalty']),
    MultiplicativeModifier('burghers_influence_modifier', ['burghers influence']),
    MultiplicativeModifier('burghers_loyalty_modifier', ['burghers loyalty']),
    MultiplicativeModifier('vaisyas_loyalty_modifier', ['vaishyas loyalty']),
    MultiplicativeModifier('brahmins_muslim_loyalty_modifier', ['brahmins muslim loyalty']),
    MultiplicativeModifier('brahmins_hindu_loyalty_modifier', ['brahmins hindu loyalty']),
    MultiplicativeModifier('brahmins_other_loyalty_modifier', ['brahmins other loyalty']),
    MultiplicativeModifier('church_loyalty_modifier', ['clergy loyalty']),
    MultiplicativeModifier('dhimmi_loyalty_modifier', ['dhimmi loyalty']),
    MultiplicativeModifier('min_autonomy_in_territories', ['minimum autonomy in territories']),
    MultiplicativeModifier('governing_capacity_modifier', ['governing capacity modifier']),
    MultiplicativeModifier('allowed_marine_fraction', ['marines force limit']),
    MultiplicativeModifier('disengagement_chance', ['ship disengagement chance']),
    MultiplicativeModifier('flagship_cost', ['flagship cost']),
    AdditiveModifier('monarch_diplomatic_power', ['monarch diplomatic skill']),
    AdditiveModifier('monarch_military_power', ['monarch military skill']),
    AdditiveModifier('max_revolutionary_zeal', ['max revolutionary zeal', 'maximum revolutionary zeal']),
    MultiplicativeModifier('general_cost', ['general cost']),
    ConstantModifier('may_recruit_female_generals', ['may recruit female generals']),
    MultiplicativeModifier('trade_company_investment_cost', ['trade company investment cost']),
    MultiplicativeModifier('drill_gain_modifier', ['army drill gain modifier']),
    MultiplicativeModifier('enforce_religion_cost', ['cost of enforcing religion through war']),
    MultiplicativeModifier('leader_cost', ['leader cost']),
    AdditiveModifier('tribal_development_growth', ['tribal development growth']),
    AdditiveModifier('accept_vassalization_reasons', ['vassalization acceptance']),

    AdditiveModifier('pr_captains_influence', ['captains influence']),
    MultiplicativeModifier('rival_change_cost', ['change rival cost']),
    AdditiveModifier('infantry_shock', ['infantry shock']),
    MultiplicativeModifier('manpower_in_true_faith_provinces', ['manpower in true faith provinces']),
    MultiplicativeModifier('migration_cost', ['migration cost']),
    MultiplicativeModifier('prestige_from_naval', ['prestige from naval battles', 'prestige from naval']),
    MultiplicativeModifier('promote_culture_cost', ['promote culture cost']),
    MultiplicativeModifier('raze_power_gain', ['razing power gain']),
    AdditiveModifier('movement_speed_in_fleet_modifier', ['ship speed']),
    MultiplicativeModifier('warscore_cost_vs_other_religion', ['war score cost vs other religions']),
    MultiplicativeModifier('yearly_karma_decay', ['yearly karma decay']),
    MultiplicativeModifier('yearly_patriarch_authority', ['yearly patriarch authority']),

    MultiplicativeModifier('nobles_influence_modifier', ['nobility influence']),
    MultiplicativeModifier('special_unit_forcelimit', ['special unit force limit']),
    AdditiveModifier('country_admin_power', ['monthly administrative power']),
    MultiplicativeModifier('jains_loyalty_modifier', ['jains loyalty']),
    MultiplicativeModifier('reduced_liberty_desire_on_other_continent', ['reduced liberty desire on other continent'], multiply_value_with=-1),
    MultiplicativeModifier('reduced_liberty_desire_on_same_continent', ['liberty desire in same continent subjects'], multiply_value_with=-1),
    AdditiveModifier('prestige_per_development_from_conversion', ['prestige per development from missionary']),
    AdditiveModifier('free_policy', ['free policies']),
    AdditiveModifier('max_absolutism', ['maximum absolutism']),
    MultiplicativeModifier('treasure_fleet_income', ['treasure fleet income']),
    MultiplicativeModifier('discovered_relations_impact', ['covert action relation impact']),
    MultiplicativeModifier('nomadic_tribes_loyalty_modifier', ['tribes loyalty']),
    MultiplicativeModifier('rajput_loyalty_modifier', ['rajputs loyalty']),
    MultiplicativeModifier('monthly_favor_modifier', ['monthly favor growth modifier']),

    # the following have no icon
    MultiplicativeModifier('all_estate_loyalty_equilibrium', ['all estates loyalty equilibrium']),
    ConstantModifier('auto_explore_adjacent_to_colony', ['auto explore adjacent to colony']),
    ConstantModifier('cb_on_primitives', ['cb on primitives']),
    ConstantModifier('cb_on_religious_enemies', ['cb on religious enemies']),
    AdditiveModifier('global_allowed_num_of_buildings', ['global possible number of buildings']),
    ConstantModifier('idea_claim_colonies', ['idea claim colonies']),
    ConstantModifier('reduced_stab_impacts', ['reduced stab impacts']),
    ConstantModifier('sea_repair', ['sea repair']),
    MultiplicativeModifier('global_supply_limit_modifier', ['national supply limit modifier']),
    AdditiveModifier('tolerance_of_heathens_capacity', ['maximum tolerance of heathens']),
    AdditiveModifier('tolerance_of_heretics_capacity', ['maximum tolerance of heretics']),
    MultiplicativeModifier('monthly_reform_progress_modifier', ['monthly reform progress modifier']),
    MultiplicativeModifier('global_naval_barrage_cost', ['naval barrage cost']),
    MultiplicativeModifier('mercantilism_cost', ['cost to promote mercantilism']),
    MultiplicativeModifier('expand_administration_cost', ['expand administration cost']),
    AdditiveModifier('max_hostile_attrition', ['max hostile attrition']),
    ConstantModifier('may_establish_frontier', ['may establish siberian frontiers']),
    ConstantModifier('can_fabricate_for_vassals', ['may fabricate claims for subjects']),
    ConstantModifier('may_perform_slave_raid_on_same_religion', ['may raid coasts including coasts of countries with same religion']),
    ConstantModifier('can_recruit_hussars', ['may recruit winged hussars']),
    AdditiveModifier('monthly_piety_accelerator', ['monthly piety accelerator'], multiply_value_with=100),
    MultiplicativeModifier('harmonization_speed', ['religious harmonization speed']),
    AdditiveModifier('yearly_authority', ['yearly authority']),
    AdditiveModifier('yearly_doom_reduction', ['yearly doom reduction']),
]

all_modifiers_by_name = {modifier.name: modifier for modifier in all_modifiers}
