from eu4.eu4lib import AdditiveModifier, ConstantModifier, MultiplicativeModifier, \
    AdditiveModifierWithPercentageSign

all_modifiers = [
    AdditiveModifier('num_accepted_cultures', ['max promoted cultures']),
    MultiplicativeModifier('adm_tech_cost_modifier', ['adm tech cost']),
    MultiplicativeModifier('advisor_cost', ['advisor cost']),
    AdditiveModifier('advisor_pool', ['possible advisors', 'advisor pool']),
    MultiplicativeModifier('ae_impact', ['aggressive expansion impact', 'ae impact']),
    AdditiveModifier('army_tradition', ['army tradition', 'yearly army tradition']),
    MultiplicativeModifier('army_tradition_decay', ['army tradition decay']),
    MultiplicativeModifier('artillery_cost', ['art cost', 'artillery cost']),
    MultiplicativeModifier('artillery_power', ['art power', 'artillery combat ability', 'artillery power']),
    MultiplicativeModifier('blockade_efficiency', ['blockade efficiency']),
    MultiplicativeModifier('build_cost', ['construction cost']),
    MultiplicativeModifier('development_cost', ['development cost']),
    MultiplicativeModifier('cavalry_cost', ['cavalry cost', 'cav cost']),
    MultiplicativeModifier('cavalry_power', ['cav power', 'cavalry combat ability', 'cavalry power']),
    AdditiveModifier('colonists', ['colonists']),
    MultiplicativeModifier('colonist_placement_chance', ['settler chance', 'colonist chance']),
    MultiplicativeModifier('core_creation', ['core-creation cost', 'core creation cost']),
    MultiplicativeModifier('culture_conversion_cost', ['culture conversion cost']),
    MultiplicativeModifier('defensiveness', ['fort defense']),
    MultiplicativeModifier('dip_tech_cost_modifier', ['dip tech cost']),
    MultiplicativeModifier('diplomatic_annexation_cost', ['diplomatic annexation cost']),
    AdditiveModifier('diplomatic_reputation', ['diplomatic reputation']),
    AdditiveModifier('diplomatic_upkeep', ['diplomatic relations', 'diplomatic upkeep']),
    AdditiveModifier('diplomats', ['diplomats']),
    MultiplicativeModifier('discipline', ['discipline']),
    MultiplicativeModifier('embargo_efficiency', ['embargo efficiency']),
    MultiplicativeModifier('enemy_core_creation', ['hostile core-creation cost on us', 'enemy core creation']),
    MultiplicativeModifier('envoy_travel_time', ['envoy travel time']),
    MultiplicativeModifier('fabricate_claims_cost', ['cost to fabricate claims']),
    AdditiveModifier('free_leader_pool', ['leader(s) without upkeep', 'free leader pool']),
    MultiplicativeModifier('galley_cost', ['galley cost']),
    MultiplicativeModifier('galley_power', ['galley combat ability', 'galley power']),
    AdditiveModifier('global_colonial_growth', ['global settler increase']),
    MultiplicativeModifier('global_foreign_trade_power', ['trade power abroad', 'foreign trade power']),
    MultiplicativeModifier('global_garrison_growth', ['national garrison growth', 'global garrison growth']),
    MultiplicativeModifier('global_heretic_missionary_strength',
                           ['missionary strength vs heretics', 'global heretic missionary strength']),
    MultiplicativeModifier('global_manpower_modifier', ['national manpower modifier', 'global manpower modifier']),
    MultiplicativeModifier('global_missionary_strength', ['missionary strength', 'global missionary strength']),
    MultiplicativeModifier('global_own_trade_power', ['domestic trade power']),
    MultiplicativeModifier('global_prov_trade_power_modifier',
                           ['provincial trade power modifier', 'global prov trade power modifier']),
    MultiplicativeModifier('global_regiment_cost', ['regiment cost']),
    MultiplicativeModifier('global_regiment_recruit_speed', ['recruitment time', 'global regiment recruit speed']),
    AdditiveModifier('global_unrest', ['national unrest', 'global unrest']),
    MultiplicativeModifier('global_ship_cost', ['ship cost']),
    MultiplicativeModifier('global_ship_recruit_speed', ['shipbuilding time', 'global ship recruit speed']),
    MultiplicativeModifier('global_ship_repair', ['global ship repair']),
    MultiplicativeModifier('global_spy_defence', ['foreign spy detection']),
    MultiplicativeModifier('global_tariffs', ['global tariffs']),
    MultiplicativeModifier('global_tax_modifier', ['national tax modifier', 'global tax modifier']),
    MultiplicativeModifier('global_trade_goods_size_modifier', ['goods produced modifier']),
    MultiplicativeModifier('global_trade_power', ['global trade power']),
    MultiplicativeModifier('great_project_upgrade_cost', ['great project upgrade cost']),
    MultiplicativeModifier('heavy_ship_cost', ['heavy ship cost']),
    MultiplicativeModifier('heavy_ship_power', ['heavy ship combat ability', 'heavy ship power']),
    MultiplicativeModifier('heir_chance', ['chance of new heir', 'heir chance']),
    AdditiveModifier('hostile_attrition', ['attrition for enemies', 'hostile attrition']),
    MultiplicativeModifier('idea_cost', ['idea cost']),
    MultiplicativeModifier('imperial_authority', ['imperial authority growth modifier']),
    AdditiveModifier('imperial_authority_value', ['imperial authority modifier']),
    MultiplicativeModifier('improve_relation_modifier', ['improve relations', 'improve relation modifier']),
    MultiplicativeModifier('infantry_cost', ['inf cost', 'infantry cost']),
    MultiplicativeModifier('infantry_power', ['inf power', 'infantry combat ability', 'infantry power']),
    AdditiveModifier('inflation_reduction', ['inflation reduction']),
    AdditiveModifier('interest', ['interest per annum', 'interest']),
    MultiplicativeModifier('justify_trade_conflict_cost',
                           ['cost to justify trade conflict', 'justify trade conflict cost']),
    MultiplicativeModifier('land_attrition', ['land attrition']),
    MultiplicativeModifier('land_forcelimit_modifier', ['land force limit modifier', 'land forcelimit modifier']),
    MultiplicativeModifier('land_maintenance_modifier', ['land maintenance modifier']),
    MultiplicativeModifier('land_morale', ['morale of armies', 'land morale']),
    AdditiveModifier('leader_land_fire', ['land leader fire']),
    AdditiveModifier('leader_land_manuever', ['land leader maneuver']),
    AdditiveModifier('leader_land_shock', ['land leader shock']),
    AdditiveModifier('leader_naval_fire', ['naval leader fire']),
    AdditiveModifier('leader_naval_manuever', ['naval leader maneuver']),
    AdditiveModifier('leader_naval_shock', ['naval leader shock']),
    AdditiveModifier('leader_siege', ['leader siege']),
    AdditiveModifier('legitimacy', ['legitimacy', 'yearly legitimacy']),
    MultiplicativeModifier('light_ship_cost', ['light ship cost']),
    MultiplicativeModifier('light_ship_power', ['light ship combat ability', 'light ship power']),
    MultiplicativeModifier('manpower_recovery_speed', ['manpower recovery speed']),
    ConstantModifier('may_explore', ['may explore']),
    ConstantModifier('may_perform_slave_raid', ['may raid coasts']),
    MultiplicativeModifier('merc_maintenance_modifier', ['mercenary maintenance', 'merc maintenance modifier']),
    MultiplicativeModifier('mercenary_cost', ['mercenary cost']),
    MultiplicativeModifier('caravan_power', ['caravan power']),
    AdditiveModifier('merchants', ['merchants']),
    MultiplicativeModifier('mil_tech_cost_modifier', ['mil tech cost']),
    AdditiveModifier('missionaries', ['missionaries']),
    AdditiveModifier('monthly_fervor_increase', ['monthly fervor', 'monthly fervor increase']),
    MultiplicativeModifier('naval_attrition', ['naval attrition']),
    MultiplicativeModifier('naval_forcelimit_modifier', ['naval force limit modifier', 'naval forcelimit modifier']),
    MultiplicativeModifier('monthly_gold_inflation_modifier', ['monthly gold inflation modifier']),
    MultiplicativeModifier('naval_maintenance_modifier', ['naval maintenance modifier']),
    MultiplicativeModifier('naval_morale', ['morale of navies', 'naval morale']),
    AdditiveModifier('navy_tradition', ['navy tradition', 'yearly navy tradition']),
    MultiplicativeModifier('navy_tradition_decay', ['navy tradition decay']),
    ConstantModifier('no_religion_penalty', ['no religion penalty']),
    AdditiveModifier('papal_influence', ['papal influence']),
    MultiplicativeModifier('mercenary_manpower', ['mercenary manpower']),
    AdditiveModifier('prestige', ['prestige']),
    MultiplicativeModifier('prestige_decay', ['prestige decay']),
    MultiplicativeModifier('prestige_from_land', ['prestige from land']),
    MultiplicativeModifier('privateer_efficiency', ['privateer efficiency']),
    MultiplicativeModifier('production_efficiency', ['production efficiency']),
    MultiplicativeModifier('range', ['colonial range']),
    MultiplicativeModifier('rebel_support_efficiency', ['rebel support efficiency']),
    MultiplicativeModifier('recover_army_morale_speed', ['land morale recovery', 'recover army morale speed']),
    MultiplicativeModifier('recover_navy_morale_speed', ['naval morale recovery', 'recover navy morale speed']),
    MultiplicativeModifier('native_assimilation', ['native assimilation']),
    MultiplicativeModifier('native_uprising_chance', ['native uprising chance']),
    MultiplicativeModifier('reinforce_speed', ['reinforce speed']),
    MultiplicativeModifier('religious_unity', ['religious unity']),
    AdditiveModifier('republican_tradition', ['republican tradition', 'yearly republican tradition']),
    MultiplicativeModifier('ship_durability', ['ship durability']),
    MultiplicativeModifier('siege_ability', ['siege ability']),
    MultiplicativeModifier('spy_offence', ['spy network construction']),
    MultiplicativeModifier('stability_cost_modifier', ['stability cost modifier']),
    MultiplicativeModifier('technology_cost', ['technology cost']),
    AdditiveModifier('tolerance_heathen', ['tolerance of heathens', 'tolerance heathen']),
    AdditiveModifier('tolerance_heretic', ['tolerance of heretics', 'tolerance heretic']),
    AdditiveModifier('tolerance_own', ['tolerance of the true faith', 'tolerance own']),
    MultiplicativeModifier('trade_efficiency', ['trade efficiency']),
    MultiplicativeModifier('trade_range_modifier', ['trade range']),
    MultiplicativeModifier('trade_steering', ['trade steering']),
    MultiplicativeModifier('unjustified_demands', ['unjustified demands']),
    MultiplicativeModifier('vassal_forcelimit_bonus', ['vassal force limit contribution', 'vassal forcelimit bonus']),
    MultiplicativeModifier('vassal_income', ['income from vassals', 'vassal income']),
    AdditiveModifier('war_exhaustion', ['monthly war exhaustion', 'war exhaustion decrease']),
    MultiplicativeModifier('war_exhaustion_cost', ['war exhaustion cost']),
    AdditiveModifier('years_of_nationalism', ['years of separatism']),
    AdditiveModifier('global_autonomy', ['autonomy', 'national autonomy']),
    MultiplicativeModifier('province_warscore_cost', ['province warscore cost', 'province war score cost']),
    AdditiveModifier('devotion', ['devotion', 'yearly devotion']),
    MultiplicativeModifier('church_power_modifier', ['church power', 'church power modifier']),
    MultiplicativeModifier('garrison_size', ['garrison size']),
    MultiplicativeModifier('fort_maintenance_modifier', ['fort maintenance', 'fort maintenance modifier']),
    MultiplicativeModifier('loot_amount', ['looting speed']),
    AdditiveModifier('horde_unity', ['horde unity', 'yearly horde unity']),
    MultiplicativeModifier('global_sailors_modifier', ['national sailors modifier']),
    MultiplicativeModifier('sailors_recovery_speed', ['sailor recovery speed']),
    MultiplicativeModifier('state_maintenance_modifier', ['state maintenance']),
    MultiplicativeModifier('reduced_liberty_desire', ['liberty desire in subjects'], multiply_value_with=-1),
    AdditiveModifier('yearly_corruption', ['corruption']),
    MultiplicativeModifier('global_institution_spread', ['institution spread']),
    MultiplicativeModifier('embracement_cost', ['institution embracement cost']),
    MultiplicativeModifier('movement_speed', ['movement speed']),
    MultiplicativeModifier('shock_damage_received', ['shock damage received']),
    MultiplicativeModifier('army_tradition_from_battle', ['army tradition from battles']),
    MultiplicativeModifier('naval_tradition_from_battle', ['naval tradition from battles']),
    AdditiveModifier('cavalry_fire', ['cavalry fire']),
    MultiplicativeModifier('cavalry_flanking', ['cavalry flanking ability']),
    MultiplicativeModifier('fire_damage', ['land fire damage']),
    MultiplicativeModifier('capture_ship_chance', ['capture ship chance', 'chance to capture enemy ships']),
    MultiplicativeModifier('sunk_ship_morale_hit_recieved', ['morale hit when losing a ship']),
    MultiplicativeModifier('transport_cost', ['transport cost']),
    AdditiveModifier('yearly_harmony', ['harmony increase', 'yearly harmony increase']),
    AdditiveModifier('yearly_absolutism', ['yearly absolutism', 'absolutism']),
    MultiplicativeModifier('cav_to_inf_ratio', ['cavalry to infantry ratio']),
    MultiplicativeModifier('amount_of_banners', ['amount of banners', 'possible manchu banners']),
    MultiplicativeModifier('reinforce_cost_modifier', ['reinforce cost']),
    MultiplicativeModifier('shock_damage', ['shock damage']),
    MultiplicativeModifier('sailor_maintenance_modifer', ['sailor maintenance']),
    MultiplicativeModifier('administrative_efficiency', ['administrative efficiency']),
    MultiplicativeModifier('global_naval_engagement_modifier', ['global naval engagement']),
    MultiplicativeModifier('mercenary_discipline', ['mercenary discipline']),
    MultiplicativeModifier('fire_damage_received', ['fire damage received']),
    AdditiveModifier('monthly_piety', ['monthly piety'], multiply_value_with=100),
    AdditiveModifier('yearly_tribal_allegiance', ['yearly tribal allegiance']),
    MultiplicativeModifier('same_culture_advisor_cost', ['cost of adv wrc']),
    AdditiveModifier('meritocracy', ['meritocracy']),
    MultiplicativeModifier('harsh_treatment_cost', ['harsh treatment cost']),
    MultiplicativeModifier('global_ship_trade_power', ['ship trade power']),
    MultiplicativeModifier('ship_power_propagation', ['ship tradepower propagation']),
    MultiplicativeModifier('build_time', ['construction time']),
    AdditiveModifier('possible_policy', ['possible policies']),
    MultiplicativeModifier('reform_progress_growth', ['reform progress growth']),
    AdditiveModifier('free_adm_policy', ['administrative free policies']),
    AdditiveModifier('free_dip_policy', ['diplomatic free policies']),
    AdditiveModifier('free_mil_policy', ['military free policies']),
    AdditiveModifier('possible_dip_policy', ['diplomatic possible policies']),
    AdditiveModifier('possible_mil_policy', ['military possible policies']),
    MultiplicativeModifier('power_projection_from_insults', ['power projection from insults']),
    MultiplicativeModifier('innovativeness_gain', ['innovativeness gain']),
    MultiplicativeModifier('missionary_maintenance_cost', ['missionary maintenance', 'missionary maintenance cost']),
    MultiplicativeModifier('expel_minorities_cost', ['expel minorities cost']),
    MultiplicativeModifier('naval_tradition_from_trade',
                           ['naval tradition from trade', 'naval tradition from protecting trade']),
    MultiplicativeModifier('admiral_cost', ['admiral cost']),
    MultiplicativeModifier('center_of_trade_upgrade_cost', ['center of trade upgrade cost']),
    MultiplicativeModifier('rival_border_fort_maintenance', ['fort maintenance on border with rival']),
    AdditiveModifier('own_coast_naval_combat_bonus', ['naval combat bonus off owned coast']),
    AdditiveModifier('artillery_fire', ['artillery fire']),
    MultiplicativeModifier('autonomy_change_time', ['autonomy change cooldown']),
    MultiplicativeModifier('backrow_artillery_damage', ['artillery damage from back row']),
    AdditiveModifier('placed_merchant_power', ['merchant trade power']),
    AdditiveModifierWithPercentageSign('liberty_desire', ['liberty desire']),
    MultiplicativeModifier('liberty_desire_from_subject_development', ['liberty desire from subjects development']),
    MultiplicativeModifier('reelection_cost', ['reelection cost']),
    MultiplicativeModifier('female_advisor_chance', ['female advisor chance']),
    AdditiveModifier('siege_blockade_progress', ['blockade impact on siege']),
    AdditiveModifier('imperial_mandate', ['mandate growth modifier']),
    MultiplicativeModifier('nobles_loyalty_modifier', ['nobility loyalty']),
    MultiplicativeModifier('burghers_influence_modifier', ['burghers influence']),
    MultiplicativeModifier('burghers_loyalty_modifier', ['burghers loyalty']),
    MultiplicativeModifier('vaisyas_loyalty_modifier', ['vaishyas loyalty']),
    MultiplicativeModifier('brahmins_muslim_loyalty_modifier', ['brahmins muslim loyalty']),
    MultiplicativeModifier('brahmins_hindu_loyalty_modifier', ['brahmins hindu loyalty']),
    MultiplicativeModifier('brahmins_other_loyalty_modifier', ['brahmins other loyalty']),
    MultiplicativeModifier('church_loyalty_modifier', ['clergy loyalty']),
    MultiplicativeModifier('dhimmi_loyalty_modifier', ['dhimmi loyalty']),
    MultiplicativeModifier('min_autonomy_in_territories', ['minimum autonomy in territories']),
    MultiplicativeModifier('governing_capacity_modifier', ['governing capacity modifier']),
    MultiplicativeModifier('allowed_marine_fraction', ['marines force limit']),
    MultiplicativeModifier('disengagement_chance', ['ship disengagement chance']),
    MultiplicativeModifier('flagship_cost', ['flagship cost']),
    AdditiveModifier('monarch_diplomatic_power', ['monarch diplomatic skill']),
    AdditiveModifier('monarch_military_power', ['monarch military skill']),
    AdditiveModifier('max_revolutionary_zeal', ['max revolutionary zeal', 'maximum revolutionary zeal']),
    MultiplicativeModifier('general_cost', ['general cost']),
    ConstantModifier('may_recruit_female_generals', ['may recruit female generals']),
    MultiplicativeModifier('trade_company_investment_cost', ['trade company investment cost']),
    MultiplicativeModifier('drill_gain_modifier', ['army drill gain modifier']),
    MultiplicativeModifier('enforce_religion_cost', ['cost of enforcing religion through war']),
    MultiplicativeModifier('leader_cost', ['leader cost']),
    AdditiveModifier('tribal_development_growth', ['tribal development growth']),
    AdditiveModifier('accept_vassalization_reasons', ['vassalization acceptance']),

    AdditiveModifier('pr_captains_influence', ['captains influence']),
    MultiplicativeModifier('rival_change_cost', ['change rival cost']),
    AdditiveModifier('infantry_shock', ['infantry shock']),
    MultiplicativeModifier('manpower_in_true_faith_provinces', ['manpower in true faith provinces']),
    MultiplicativeModifier('migration_cost', ['migration cost']),
    MultiplicativeModifier('prestige_from_naval', ['prestige from naval battles', 'prestige from naval']),
    MultiplicativeModifier('promote_culture_cost', ['promote culture cost']),
    MultiplicativeModifier('raze_power_gain', ['razing power gain']),
    AdditiveModifier('movement_speed_in_fleet_modifier', ['ship speed']),
    MultiplicativeModifier('warscore_cost_vs_other_religion', ['war score cost vs other religions']),
    MultiplicativeModifier('yearly_karma_decay', ['yearly karma decay']),
    MultiplicativeModifier('yearly_patriarch_authority', ['yearly patriarch authority']),

    MultiplicativeModifier('nobles_influence_modifier', ['nobility influence']),
    MultiplicativeModifier('special_unit_forcelimit', ['special unit force limit']),
    AdditiveModifier('country_admin_power', ['monthly administrative power']),
    MultiplicativeModifier('jains_loyalty_modifier', ['jains loyalty']),
    MultiplicativeModifier('reduced_liberty_desire_on_other_continent', ['reduced liberty desire on other continent'],
                           multiply_value_with=-1),
    MultiplicativeModifier('reduced_liberty_desire_on_same_continent', ['liberty desire in same continent subjects'],
                           multiply_value_with=-1),
    AdditiveModifier('prestige_per_development_from_conversion', ['prestige per development from missionary']),
    AdditiveModifier('free_policy', ['free policies']),
    AdditiveModifier('max_absolutism', ['maximum absolutism']),
    MultiplicativeModifier('treasure_fleet_income', ['treasure fleet income']),
    MultiplicativeModifier('discovered_relations_impact', ['covert action relation impact']),
    MultiplicativeModifier('nomadic_tribes_loyalty_modifier', ['tribes loyalty']),
    MultiplicativeModifier('rajput_loyalty_modifier', ['rajputs loyalty']),
    MultiplicativeModifier('monthly_favor_modifier', ['monthly favor growth modifier']),

    MultiplicativeModifier('adm_advisor_cost', ['administrative advisor cost']),
    AdditiveModifier('all_estate_possible_privileges', ['max privileges per estate']),
    ConstantModifier('allow_client_states', ['can create §yclient states§!']),
    ConstantModifier('allow_mercenary_drill', ['allow mercenary units to drill']),
    MultiplicativeModifier('allowed_samurai_fraction', ['samurai force limit fraction']),
    AdditiveModifier('artillery_level_modifier', ['artillery levels contribution to siege']),
    AdditiveModifier('artillery_levels_available_vs_fort', ['artillery levels available vs fort']),
    AdditiveModifier('artillery_shock', ['artillery shock']),
    ConstantModifier('can_chain_claim', ['allow claims bordering claims']),
    ConstantModifier('can_claim_states', ['can claim entire states']),
    ConstantModifier('can_transfer_vassal_wargoal', ['allows transfer subject peace treaty at half cost']),
    AdditiveModifier('coast_raid_range', ['coastal raiding range']),
    AdditiveModifier('colony_development_boost', ['colony development boost']),
    AdditiveModifier('cossacks_privilege_slots', ['cossacks max privileges']),
    MultiplicativeModifier('curia_powers_cost', ['curia powers cost']),
    MultiplicativeModifier('development_cost_in_primary_culture', ['development cost in primary culture']),
    MultiplicativeModifier('dip_advisor_cost', ['diplomatic advisor cost']),
    MultiplicativeModifier('estate_interaction_cooldown_modifier', ['estate interaction cooldown modifier']),
    MultiplicativeModifier('eunuchs_loyalty_modifier', ['eunuchs loyalty']),
    MultiplicativeModifier('expand_infrastructure_cost_modifier', ['expand infrastructure cost modifier']),
    ConstantModifier('force_march_free', ['force march costs no power']),
    MultiplicativeModifier('garrison_damage', ['garrison army damage']),
    AdditiveModifier('global_monthly_devastation', ['global monthly devastation']),
    AdditiveModifier('global_prosperity_growth', ['global prosperity growth']),
    MultiplicativeModifier('global_rebel_suppression_efficiency', ['rebel suppression efficiency']),
    MultiplicativeModifier('gold_depletion_chance_modifier', ['gold depletion chance modifier']),
    ConstantModifier('has_geobukseon', ['country allows geobukseon ships']),
    ConstantModifier('has_samurai', ['country allows samurai infantry']),
    MultiplicativeModifier('janissaries_loyalty_modifier', ['janissary loyalty']),
    AdditiveModifier('landing_penalty', ['combat penalty when landing']),
    MultiplicativeModifier('loyalty_change_on_revoked', ['estate loyalty change on privilege revoked']),
    MultiplicativeModifier('maratha_loyalty_modifier', ['marathas loyalty']),
    AdditiveModifier('max_admiral_maneuver', ['max admiral maneuver']),
    ConstantModifier('may_build_supply_depot', ['may build supply depots']),
    ConstantModifier('merc_independent_from_trade_range', ['can recruit mercenaries from anywhere']),
    MultiplicativeModifier('merc_leader_army_tradition', ['mercenary leader army tradition modifier']),
    MultiplicativeModifier('mil_advisor_cost', ['military advisor cost']),
    AdditiveModifier('military_tactics', ['military tactics']),
    MultiplicativeModifier('monarch_lifespan', ['average monarch lifespan']),
    AdditiveModifier('monthly_federation_favor_growth', ['monthly federation favor growth']),
    AdditiveModifier('monthly_reform_progress', ['monthly reform progress']),
    AdditiveModifier('monthly_splendor', ['monthly splendor']),
    MultiplicativeModifier('morale_damage', ['morale damage']),
    MultiplicativeModifier('morale_damage_received', ['morale damage received']),
    ConstantModifier('no_stability_loss_on_monarch_death', ['no stability loss on monarch death']),
    AdditiveModifier('num_of_parliament_issues', ['number of possible parliament issues']),
    MultiplicativeModifier('overextension_impact_modifier', ['overextension impact modifier']),
    MultiplicativeModifier('possible_condottieri', ['possible condottieri']),
    MultiplicativeModifier('regiment_manpower_usage', ['regiment manpower usage']),
    AdditiveModifier('reverse_relation_with_same_religion', ['others of the same religion opinion of country']),
    MultiplicativeModifier('special_unit_cost_modifier', ['special unit cost modifier']),
    MultiplicativeModifier('spy_action_cost_modifier', ['spy action cost modifier']),
    AdditiveModifier('stability_cost_to_declare_war', ['stability hit to declare war']),
    MultiplicativeModifier('state_governing_cost', ['state governing cost']),
    MultiplicativeModifier('trade_company_governing_cost', ['trade company governing cost']),
    MultiplicativeModifier('transport_attrition', ['attrition when loaded on ships']),
    MultiplicativeModifier('vassal_naval_forcelimit_bonus', ['vassal naval force limit contribution']),
    MultiplicativeModifier('war_taxes_cost_modifier', ['war taxes cost']),
    MultiplicativeModifier('yearly_army_professionalism', ['yearly army professionalism']),
    AdditiveModifier('yearly_government_power', ['yearly government power']),
    AdditiveModifier('years_to_integrate_personal_union', ['years for personal union integration']),
    MultiplicativeModifier('add_tribal_land_cost', ['add tribal land cost']),
    MultiplicativeModifier('admiral_skill_gain_modifier', ['monthly chance of admiral skill gain on mission']),
    MultiplicativeModifier('all_estate_influence_modifier', ['all estates influence modifier']),
    MultiplicativeModifier('all_power_cost', ['all power costs']),
    ConstantModifier('allow_free_estate_privilege_revocation',
                     ['allow estate privileges to be revoked regardless of loyalty and influence']),
    ConstantModifier('allow_janissaries_from_own_faith', ['allow janissaries in true faith provinces']),
    MultiplicativeModifier('allowed_caravel_fraction', ['caravel force limit']),
    MultiplicativeModifier('allowed_cossack_fraction', ['cossack force limit fraction']),
    MultiplicativeModifier('allowed_galleass_fraction', ['galleass force limit']),
    MultiplicativeModifier('allowed_galleon_fraction', ['galleon force limit']),
    MultiplicativeModifier('allowed_geobukseon_fraction', ['geobukseon force limit']),
    MultiplicativeModifier('allowed_man_of_war_fraction', ['man of war force limit']),
    MultiplicativeModifier('allowed_musketeer_fraction', ['musketeer force limit']),
    AdditiveModifier('allowed_num_of_buildings', ['possible number of buildings']),
    AdditiveModifier('allowed_num_of_manufactories', ['possible number of manufactories']),
    MultiplicativeModifier('allowed_rajput_fraction', ['rajput force limit fraction']),
    MultiplicativeModifier('allowed_streltsy_fraction', ['streltsy force limit fraction']),
    MultiplicativeModifier('allowed_tercio_fraction', ['tercio force limit fraction']),
    MultiplicativeModifier('allowed_voc_indiamen_fraction', ['voc indiamen force limit']),
    MultiplicativeModifier('amount_of_carolean', ['possible carolean infantry']),
    MultiplicativeModifier('amount_of_cawa', ['possible cawa']),
    AdditiveModifier('amount_of_hussars', ['possible winged hussars']),
    AdditiveModifier('amount_of_samurai', ['samurai force limit']),
    MultiplicativeModifier('annexation_relations_impact', ['annexation relations impact']),
    MultiplicativeModifier('appoint_cardinal_cost', ['appoint cardinal cost']),
    MultiplicativeModifier('artillery_barrage_cost', ['artillery barrage cost']),
    MultiplicativeModifier('assault_fort_ability', ['assault fort ability']),
    ConstantModifier('attack_bonus_in_capital_terrain', ['combat bonus in terrain of capital: +1']),
    MultiplicativeModifier('available_province_loot', ['available loot']),
    MultiplicativeModifier('barrage_cost_in_fleet_modifier', ['fleet naval barrage cost']),
    ConstantModifier('block_introduce_heir', ['blocks introduce new heir']),
    ConstantModifier('block_slave_raid', ['blocks slave raids']),
    MultiplicativeModifier('blockade_force_required', ['blockade force required']),
    AdditiveModifier('blockade_impact_on_siege_in_fleet_modifier', ['fleet blockade impact on siege']),
    MultiplicativeModifier('brahmins_hindu_influence_modifier', ['brahmins influence']),
    MultiplicativeModifier('brahmins_muslim_influence_modifier', ['brahmins influence']),
    MultiplicativeModifier('brahmins_other_influence_modifier', ['brahmins influence']),
    AdditiveModifier('bureaucrats_influence', ['bureaucrats influence']),
    AdditiveModifier('burghers_privilege_slots', ['burghers max privileges']),
    ConstantModifier('can_not_declare_war', ['can not declare war']),
    ConstantModifier('can_recruit_janissaries', ['can recruit janissaries']),
    ConstantModifier('can_recruit_rajputs', ['can recruit rajputs']),
    ConstantModifier('can_revoke_parliament_seats', ['can revoke seats in parliament']),
    ConstantModifier('can_transport_units', ['can transport units']),
    AdditiveModifier('candidate_random_bonus', ['random candidate bonus']),
    MultiplicativeModifier('cannons_for_hunting_pirates_in_fleet', ['fleet hunt pirates efficiency']),
    AdditiveModifier('cavalry_shock', ['cavalry shock']),
    MultiplicativeModifier('centralize_state_cost', ['centralize state cost']),
    MultiplicativeModifier('chance_to_inherit', ['chance to inherit personal union subjects']),
    MultiplicativeModifier('church_influence_modifier', ['clergy influence']),
    AdditiveModifier('church_privilege_slots', ['clergy max privileges']),
    MultiplicativeModifier('colonial_subject_type_upgrade_cost_modifier',
                           ['colonial subject type upgrade cost modifier']),
    MultiplicativeModifier('colonial_type_change_cost_modifier', ['colonial type change cost modifier']),
    MultiplicativeModifier('colony_cost_modifier', ['colony cost modifier']),
    AdditiveModifier('combat_width', ['combat width']),
    MultiplicativeModifier('core_decay_on_your_own', ['foreign core duration']),
    MultiplicativeModifier('cossacks_influence_modifier', ['cossacks influence']),
    MultiplicativeModifier('cossacks_loyalty_modifier', ['cossacks loyalty']),
    AdditiveModifier('country_diplomatic_power', ['monthly diplomatic power']),
    AdditiveModifier('country_military_power', ['monthly military power']),
    MultiplicativeModifier('culture_conversion_time', ['culture conversion time']),
    MultiplicativeModifier('curia_treasury_contribution', ['curia treasury contribution']),
    MultiplicativeModifier('development_cost_modifier', ['development cost modifier']),
    MultiplicativeModifier('dhimmi_influence_modifier', ['dhimmi influence']),
    AdditiveModifier('dhimmi_privilege_slots', ['dhimmi max privileges']),
    MultiplicativeModifier('drill_decay_modifier', ['regiment drill loss']),
    AdditiveModifier('election_cycle', ['length of election term']),
    AdditiveModifier('enuchs_influence', ['eunuchs influence']),
    MultiplicativeModifier('establish_order_cost', ['none']),
    MultiplicativeModifier('eunuchs_influence_modifier', ['eunuchs influence']),
    AdditiveModifier('eunuchs_privilege_slots', ['eunuchs max privileges']),
    AdditiveModifier('exploration_mission_range_in_fleet_modifier', ['fleet exploration range']),
    ConstantModifier('extra_manpower_at_religious_war', ['triple manpower increase in religious wars.']),
    MultiplicativeModifier('flagship_durability', ['flagship durability']),
    MultiplicativeModifier('flagship_morale', ['flagship morale']),
    AdditiveModifier('flagship_naval_engagement_modifier', ['fleet engagement width']),
    AdditiveModifier('fort_level', ['fort level']),
    MultiplicativeModifier('free_city_imperial_authority', ['imperial authority from free cities']),
    AdditiveModifier('free_land_leader_pool', ['land leader(s) without upkeep']),
    AdditiveModifier('free_navy_leader_pool', ['navy leader(s) without upkeep']),
    MultiplicativeModifier('garrison_growth', ['garrison growth']),
    AdditiveModifier('global_attacker_dice_roll_bonus', ['global attacker dice roll bonus']),
    AdditiveModifier('global_defender_dice_roll_bonus', ['global defender dice roll bonus']),
    MultiplicativeModifier('global_heathen_missionary_strength', ['missionary strength vs heathens']),
    AdditiveModifier('global_manpower', ['manpower'], multiply_value_with=1000),
    MultiplicativeModifier('global_religious_conversion_resistance', ['resistance to reformation']),
    AdditiveModifier('global_sailors', ['sailor increase']),
    AdditiveModifier('global_tax_income', ['yearly tax income']),
    AdditiveModifier('global_trade_goods_size', ['goods produced']),
    AdditiveModifier('governing_capacity', ['governing capacity']),
    MultiplicativeModifier('great_project_upgrade_time', ['great project upgrade time']),
    ConstantModifier('has_banners', ['allows banners']),
    ConstantModifier('has_caravel', ['country allows caravel ships']),
    ConstantModifier('has_carolean', ['allows carolean infantry']),
    ConstantModifier('has_galleass', ['country allows galleass ships']),
    ConstantModifier('has_galleon', ['country allows galleon ships']),
    ConstantModifier('has_man_of_war', ['country allows man of war ships']),
    ConstantModifier('has_musketeer', ['country allows musketeer infantry']),
    ConstantModifier('has_streltsy', ['country allows streltsy infantry']),
    ConstantModifier('has_tercio', ['country allows tercio infantry']),
    ConstantModifier('has_voc_indiamen', ['country allows voc indiamen ships']),
    MultiplicativeModifier('hostile_disembark_speed', ['hostile disembark time']),
    AdditiveModifier('hostile_fleet_attrition', ['hostile fleet attrition']),
    MultiplicativeModifier('hull_size_modifier', ['hull size']),
    ConstantModifier('ignore_coring_distance', ['ignore coring distance']),
    MultiplicativeModifier('imperial_mercenary_cost', ['hre mercenary recruitment cost']),
    AdditiveModifier('imperial_reform_catholic_approval', ['approval of imperial reforms by catholic princes']),
    AdditiveModifier('infantry_fire', ['infantry fire']),
    MultiplicativeModifier('inflation_action_cost', ['reduce inflation cost']),
    AdditiveModifier('institution_growth', ['institution growth']),
    MultiplicativeModifier('institution_spread_from_true_faith', ['institution spread in true faith provinces']),
    MultiplicativeModifier('jains_influence_modifier', ['jains influence']),
    MultiplicativeModifier('janissaries_influence_modifier', ['janissary influence']),
    AdditiveModifier('janissaries_privilege_slots', ['janissary max privileges']),
    MultiplicativeModifier('janissary_cost_modifier', ['janissary regiment cost']),
    AdditiveModifier('land_forcelimit', ['land force limit']),
    AdditiveModifier('legitimate_subject_elector', ['legitimate subject elector']),
    AdditiveModifier('local_amount_of_banners', ['possible manchu banners']),
    AdditiveModifier('local_amount_of_carolean', ['possible carolean infantry from development']),
    AdditiveModifier('local_amount_of_cawa', ['possible cawa (local)']),
    AdditiveModifier('local_amount_of_hussars', ['possible winged hussars from development']),
    AdditiveModifier('local_autonomy', ['monthly autonomy change']),
    MultiplicativeModifier('local_build_cost', ['local construction cost']),
    MultiplicativeModifier('local_build_time', ['local construction time']),
    MultiplicativeModifier('local_center_of_trade_upgrade_cost', ['local center of trade upgrade cost']),
    MultiplicativeModifier('local_centralize_state_cost', ['local centralize state cost']),
    AdditiveModifier('local_colonial_growth', ['local settler increase']),
    MultiplicativeModifier('local_colonist_placement_chance', ['local settler chance']),
    MultiplicativeModifier('local_core_creation', ['local core-creation cost']),
    MultiplicativeModifier('local_culture_conversion_cost', ['local culture conversion cost']),
    AdditiveModifier('local_defender_dice_roll_bonus', ['local defender dice roll bonus']),
    MultiplicativeModifier('local_defensiveness', ['local defensiveness']),
    MultiplicativeModifier('local_development_cost', ['local development cost']),
    MultiplicativeModifier('local_development_cost_modifier', ['local development cost modifier']),
    MultiplicativeModifier('local_fort_maintenance_modifier', ['local fort maintenance']),
    MultiplicativeModifier('local_friendly_movement_speed', ['friendly movement speed']),
    MultiplicativeModifier('local_garrison_damage', ['local garrison army damage']),
    MultiplicativeModifier('local_garrison_size', ['local garrison size']),
    MultiplicativeModifier('local_gold_depletion_chance_modifier', ['local gold depletion chance modifier']),
    MultiplicativeModifier('local_governing_cost', ['province governing cost']),
    AdditiveModifier('local_governing_cost_increase', ['province governing cost']),
    MultiplicativeModifier('local_great_project_upgrade_cost', ['great project upgrade cost']),
    MultiplicativeModifier('local_great_project_upgrade_time', ['local great project upgrade time']),
    ConstantModifier('local_has_banners', ['allows banners']),
    ConstantModifier('local_has_galleass', ['province allows galleass ships']),
    ConstantModifier('local_has_geobukseon', ['province allows geobukseon ships']),
    ConstantModifier('local_has_man_of_war', ['province allows man of war ships']),
    ConstantModifier('local_has_musketeers', ['province allows musketeer infantry']),
    ConstantModifier('local_has_streltsy', ['province allows streltsy infantry']),
    ConstantModifier('local_has_voc_indiamen', ['province allows voc indiamen ships']),
    AdditiveModifier('local_heir_adm', ['local heir administrative skill']),
    AdditiveModifier('local_heir_dip', ['local heir diplomatic skill']),
    AdditiveModifier('local_heir_mil', ['local heir military skill']),
    AdditiveModifier('local_hostile_attrition', ['attrition for enemies']),
    MultiplicativeModifier('local_hostile_movement_speed', ['hostile movement speed']),
    MultiplicativeModifier('local_institution_spread', ['institution spread']),
    AdditiveModifier('local_manpower', ['local manpower']),
    MultiplicativeModifier('local_manpower_modifier', ['local manpower modifier']),
    MultiplicativeModifier('local_missionary_maintenance_cost', ['local missionary maintenance']),
    MultiplicativeModifier('local_missionary_strength', ['local missionary strength']),
    AdditiveModifier('local_monthly_devastation', ['monthly devastation']),
    MultiplicativeModifier('local_naval_engagement_modifier', ['local naval engagement']),
    AdditiveModifier('local_own_coast_naval_combat_bonus', ['naval combat local bonus off owned coast']),
    MultiplicativeModifier('local_production_efficiency', ['local production efficiency']),
    AdditiveModifier('local_prosperity_growth', ['local prosperity growth']),
    MultiplicativeModifier('local_regiment_cost', ['local regiment cost']),
    MultiplicativeModifier('local_religious_conversion_resistance', ['resistance to reformation']),
    MultiplicativeModifier('local_religious_unity_contribution', ['local religious unity contribution']),
    AdditiveModifier('local_sailors', ['sailor increase']),
    MultiplicativeModifier('local_sailors_modifier', ['local sailors modifier']),
    MultiplicativeModifier('local_ship_cost', ['local ship cost']),
    MultiplicativeModifier('local_ship_repair', ['local ship repair']),
    MultiplicativeModifier('local_state_maintenance_modifier', ['state maintenance']),
    MultiplicativeModifier('local_tax_modifier', ['local tax modifier']),
    AdditiveModifier('local_tolerance_of_heathens', ['local tolerance of heathens']),
    AdditiveModifier('local_tolerance_of_heretics', ['local tolerance of heretics']),
    AdditiveModifier('local_unrest', ['local unrest']),
    MultiplicativeModifier('local_warscore_cost_modifier', ['war score cost']),
    AdditiveModifier('local_years_of_nationalism', ['years of separatism']),
    MultiplicativeModifier('maneuver_value', ['improved flanking range']),
    AdditiveModifier('manpower_against_imperial_enemies', ['manpower against imperial enemies']),
    MultiplicativeModifier('manpower_in_accepted_culture_provinces', ['manpower in accepted culture provinces']),
    MultiplicativeModifier('manpower_in_culture_group_provinces', ['manpower in same culture group provinces']),
    MultiplicativeModifier('manpower_in_own_culture_provinces', ['manpower in primary culture provinces']),
    MultiplicativeModifier('maratha_exclusive_influence_modifier', ['marathas influence']),
    MultiplicativeModifier('maratha_exclusive_loyalty_modifier', ['marathas loyalty']),
    MultiplicativeModifier('maratha_influence_modifier', ['marathas influence']),
    MultiplicativeModifier('maratha_muslim_influence_modifier', ['marathas influence']),
    AdditiveModifier('maratha_privilege_slots', ['marathas max privileges']),
    MultiplicativeModifier('max_absolutism_effect', ['max effect of absolutism']),
    AdditiveModifier('max_admiral_fire', ['max admiral fire']),
    AdditiveModifier('max_attrition', ['maximum attrition']),
    AdditiveModifier('max_electors', ['number of electors']),
    AdditiveModifier('max_flagships', ['max number of flagships']),
    AdditiveModifier('max_free_cities', ['number of free cities']),
    AdditiveModifier('max_possible_parliament_seats', ['max possible parliament seats']),
    ConstantModifier('may_refill_garrison', ['may refill garrison']),
    ConstantModifier('may_return_manpower_on_disband', ['regain manpower when disbanding']),
    AdditiveModifier('min_autonomy', ['minimum autonomy']),
    AdditiveModifier('min_local_autonomy', ['minimum local autonomy']),
    AdditiveModifier('monarch_admin_power', ['monarch administrative skill']),
    AdditiveModifier('monarch_power_tribute', ['monarch power tribute from tributary states']),
    AdditiveModifier('monthly_church_power', ['monthly faith power']),
    AdditiveModifier('monthly_council_consensus', ['monthly council consensus']),
    AdditiveModifier('monthly_heir_claim_increase', ['monthly heir claim increase']),
    AdditiveModifier('monthly_karma', ['monthly karma']),
    AdditiveModifier('monthly_militarized_society', ['militarization of state']),
    AdditiveModifier('monthly_ottoman_decadence', ['monthly decadence']),
    AdditiveModifier('monthly_prussian_militarized_society_1', ['monthly early prussian militarized society']),
    AdditiveModifier('monthly_prussian_militarized_society_2', ['monthly prussian militarized society']),
    AdditiveModifier('monthly_prussian_militarized_society_3', ['monthly total prussian militarized society']),
    AdditiveModifier('monthly_reform_progress_building', ['monthly reform progress']),
    AdditiveModifier('monthly_russian_adm_power', ['monthly sudebnik progress']),
    AdditiveModifier('monthly_russian_dip_power', ['monthly oprichnina progress']),
    AdditiveModifier('monthly_russian_mil_power', ['monthly streltsy progress']),
    AdditiveModifier('monthly_russian_modernization', ['monthly modernization']),
    AdditiveModifier('monthly_support_heir_gain', ['monthly heir support gain']),
    MultiplicativeModifier('morale_in_fleet_modifier', ['fleet morale']),
    MultiplicativeModifier('move_capital_cost_modifier', ['move capital cost modifier']),
    MultiplicativeModifier('movement_speed_onto_off_boat_modifier', ['movement speed on and off ships']),
    AdditiveModifier('mr_aristocrats_influence', ['aristocrats influence']),
    AdditiveModifier('mr_guilds_influence', ['guilds influence']),
    AdditiveModifier('mr_traders_influence', ['traders influence']),
    AdditiveModifier('national_focus_years', ['change national focus cooldown years']),
    MultiplicativeModifier('naval_attrition_in_fleet_modifier', ['fleet attrition']),
    AdditiveModifier('naval_engagement_width', ['engagement width']),
    AdditiveModifier('naval_forcelimit', ['naval force limit']),
    MultiplicativeModifier('naval_maintenance', ['naval maintenance']),
    AdditiveModifier('naval_maintenance_flagship_modifier', ['flagship maintenance']),
    MultiplicativeModifier('naval_morale_damage', ['naval morale damage']),
    MultiplicativeModifier('naval_tradition_in_fleet_modifier', ['fleet naval tradition from battles']),
    ConstantModifier('no_claim_cost_increasement', ['no additional claim cost']),
    AdditiveModifier('nobles_privilege_slots', ['nobility max privileges']),
    MultiplicativeModifier('nomadic_tribes_influence_modifier', ['tribes influence']),
    MultiplicativeModifier('number_of_cannons_flagship_modifier', ['flagship cannons']),
    MultiplicativeModifier('number_of_cannons_modifier', ['ship cannons']),
    MultiplicativeModifier('ottoman_decadence_gain_modifier', ['decadence gain modifier']),
    MultiplicativeModifier('overlord_naval_forcelimit_modifier', ['overlord naval force limit']),
    AdditiveModifier('own_territory_dice_roll_bonus', ['own territory dice roll bonus']),
    MultiplicativeModifier('papal_influence_from_cardinals', ['papal influence from cardinals']),
    MultiplicativeModifier('parliament_backing_chance', ['parliament debate backing chance']),
    MultiplicativeModifier('parliament_chance_of_decision', ['parliament chance of decision']),
    AdditiveModifier('parliament_debate_duration', ['parliament debate duration']),
    AdditiveModifier('parliament_effect_duration', ['parliament effect duration']),
    AdditiveModifier('possible_adm_policy', ['administrative possible policies']),
    AdditiveModifier('pr_buccaneers_influence', ['buccaneers influence']),
    AdditiveModifier('pr_smugglers_influence', ['smugglers influence']),
    MultiplicativeModifier('prestige_from_battles_in_fleet_modifier', ['fleet prestige from battles']),
    MultiplicativeModifier('privateering_efficiency_in_fleet_modifier', ['fleet privateering efficiency']),
    MultiplicativeModifier('province_trade_power_modifier', ['local trade power modifier']),
    AdditiveModifier('province_trade_power_value', ['local trade power']),
    MultiplicativeModifier('rajput_exclusive_influence_modifier', ['rajputs influence']),
    MultiplicativeModifier('rajput_exclusive_loyalty_modifier', ['rajputs loyalty']),
    MultiplicativeModifier('rajput_influence_modifier', ['rajputs influence']),
    MultiplicativeModifier('rajput_muslim_influence_modifier', ['rajputs influence']),
    AdditiveModifier('rajput_privilege_slots', ['rajputs max privileges']),
    AdditiveModifier('reasons_to_elect', ['reasons to elect']),
    ConstantModifier('reduced_naval_attrition',
                     ['the naval attrition is no longer increased by staying out at sea each month']),
    MultiplicativeModifier('reduced_trade_penalty_on_non_main_tradenode',
                           ['reduced trade penalty on non main trade node']),
    MultiplicativeModifier('regiment_disembark_speed', ['disembark time']),
    MultiplicativeModifier('regiment_recruit_speed', ['recruitment time']),
    AdditiveModifier('relation_with_heretics', ['opinion of heretics']),
    AdditiveModifier('relation_with_same_religion', ['opinion of same religion']),
    MultiplicativeModifier('reserves_organisation', ['reduced morale damage taken by reserves']),
    AdditiveModifier('rr_girondists_influence', ['girondist influence']),
    AdditiveModifier('rr_jacobins_influence', ['jacobin influence']),
    AdditiveModifier('rr_royalists_influence', ['imperial influence']),
    MultiplicativeModifier('russian_modernization_gain_modifier', ['modernization gain modifier']),
    MultiplicativeModifier('same_religion_advisor_cost', ["cost of advisors with ruler's religion"]),
    MultiplicativeModifier('settle_cost', ['settle cost']),
    MultiplicativeModifier('ship_recruit_speed', ['shipbuilding time']),
    MultiplicativeModifier('ship_trade_power_modifier', ['ship trade power modifier']),
    MultiplicativeModifier('statewide_governing_cost', ['statewide governing cost']),
    MultiplicativeModifier('supply_limit', ['supply limit']),
    MultiplicativeModifier('supply_limit_modifier', ['supply limit modifier']),
    AdditiveModifier('tax_income', ['yearly tax income']),
    AdditiveModifier('temples_influence', ['temples influence']),
    AdditiveModifier('trade_goods_size', ['local goods produced']),
    MultiplicativeModifier('trade_goods_size_modifier', ['local goods produced modifier']),
    AdditiveModifier('trade_power_in_fleet_modifier', ['trade power per ship in fleet']),
    AdditiveModifier('trade_range', ['trade range']),
    AdditiveModifier('trade_value', ['trade value']),
    MultiplicativeModifier('trade_value_modifier', ['trade value modifier']),
    AdditiveModifier('transfer_trade_power_reasons', ['transfer trade acceptance']),
    AdditiveModifier('unrest_catholic_provinces', ['unrest in catholic provinces']),
    MultiplicativeModifier('vaisyas_influence_modifier', ['vaishyas influence']),
    MultiplicativeModifier('vaisyas_non_muslim_influence_modifier', ['vaishyas influence']),
    MultiplicativeModifier('vassal_manpower_bonus', ['vassal manpower contribution']),
    MultiplicativeModifier('warscore_from_battles_modifier', ['war score from battles modifier']),
    AdditiveModifier('yearly_innovativeness', ['yearly innovativeness']),
    AdditiveModifier('yearly_revolutionary_zeal', ['revolutionary zeal']),
    MultiplicativeModifier('allowed_mamluks_fraction', ['mamluks force limit fraction']),
    MultiplicativeModifier('allowed_qizilbash_fraction', ['qizilbash force limit fraction']),
    MultiplicativeModifier('allowed_rev_guard_fraction', ['revolutionary guard force limit fraction']),
    AdditiveModifier('amount_of_qizilbash', ['qizilbash force limit']),
    AdditiveModifier('attrition', ['attrition']),
    ConstantModifier('can_not_build_missionaries', ['can not send missionaries']),
    ConstantModifier('free_concentrate_development', ['can concentrate development with no losses.']),
    MultiplicativeModifier('ghulams_influence_modifier', ['ghilman influence']),
    MultiplicativeModifier('ghulams_loyalty_modifier', ['ghilman loyalty']),
    AdditiveModifier('ghulams_privilege_slots', ['ghilman max privileges']),
    ConstantModifier('has_mamluks', ['country allows mamluks']),
    ConstantModifier('has_marines', ['country allows marine infantry']),
    ConstantModifier('has_qizilbash', ['country allows qizilbash']),
    AdditiveModifier('influence_to_vassal_elevation_cost', ['elevation cost']),
    MultiplicativeModifier('local_assault_fort_ability', ['local assault fort ability']),
    MultiplicativeModifier('local_culture_conversion_time', ['local culture conversion time']),
    ConstantModifier('local_has_mamluks', ['province allows mamluks']),
    ConstantModifier('local_has_qizilbash', ['province allows qizilbash']),
    AdditiveModifier('max_general_fire', ['max general fire']),
    AdditiveModifier('monthly_asha_vahishta', ['monthly asha vahishta']),
    AdditiveModifier('monthly_egyptian_westernization', ['monthly egyptian westernization']),
    AdditiveModifier('monthly_persian_influence', ['monthly persian influence']),
    AdditiveModifier('nomadic_tribes_privilege_slots', ['tribes max privileges']),
    AdditiveModifier('num_of_pronoiars', ['number of pronoiars']),
    MultiplicativeModifier('placed_merchant_power_modifier', ['placed merchant power modifier']),
    MultiplicativeModifier('qizilbash_influence_modifier', ['qizilbash influence']),
    MultiplicativeModifier('qizilbash_loyalty_modifier', ['qizilbash loyalty']),
    AdditiveModifier('qizilbash_privilege_slots', ['qizilbash max privileges']),
    # the following have no icon
    MultiplicativeModifier('all_estate_loyalty_equilibrium', ['all estates loyalty equilibrium']),
    ConstantModifier('auto_explore_adjacent_to_colony', ['auto explore adjacent to colony']),
    ConstantModifier('cb_on_primitives', ['cb on primitives']),
    ConstantModifier('cb_on_religious_enemies', ['cb on religious enemies']),
    AdditiveModifier('global_allowed_num_of_buildings', ['global possible number of buildings']),
    ConstantModifier('idea_claim_colonies', ['idea claim colonies']),
    ConstantModifier('reduced_stab_impacts', ['reduced stab impacts']),
    ConstantModifier('sea_repair', ['sea repair']),
    MultiplicativeModifier('global_supply_limit_modifier', ['national supply limit modifier']),
    AdditiveModifier('tolerance_of_heathens_capacity', ['maximum tolerance of heathens']),
    AdditiveModifier('tolerance_of_heretics_capacity', ['maximum tolerance of heretics']),
    MultiplicativeModifier('monthly_reform_progress_modifier', ['monthly reform progress modifier']),
    MultiplicativeModifier('global_naval_barrage_cost', ['naval barrage cost']),
    MultiplicativeModifier('mercantilism_cost', ['cost to promote mercantilism']),
    MultiplicativeModifier('expand_administration_cost', ['expand administration cost']),
    AdditiveModifier('max_hostile_attrition', ['max hostile attrition']),
    ConstantModifier('may_establish_frontier', ['may establish siberian frontiers']),
    ConstantModifier('can_fabricate_for_vassals', ['may fabricate claims for subjects']),
    ConstantModifier('may_perform_slave_raid_on_same_religion', ['may raid coasts including coasts of countries with same religion']),
    ConstantModifier('can_recruit_hussars', ['may recruit winged hussars']),
    AdditiveModifier('monthly_piety_accelerator', ['monthly piety accelerator'], multiply_value_with=100),
    MultiplicativeModifier('harmonization_speed', ['religious harmonization speed']),
    AdditiveModifier('yearly_authority', ['yearly authority']),
    AdditiveModifier('yearly_doom_reduction', ['yearly doom reduction']),
]

all_modifiers_by_name = {modifier.name: modifier for modifier in all_modifiers}
